import {
  generateSchedule,
  getScheduleAnalysis,
  optimizeScheduling,
} from '../../src/modules/scheduling/schedulingService.js';
import { truncateAll, disconnectPrisma } from '../utils/db.js';
import { seedOptimizationShowcaseScenario } from '../utils/optimizationShowcaseSeed.js';

describe('FEIT Optimization Spring 2027', () => {
  afterAll(async () => {
    await disconnectPrisma();
  });

  beforeEach(async () => {
    await truncateAll();
  });

  it('reports baseline and optimized metrics for the dedicated showcase semester', async () => {
    const scenario = await seedOptimizationShowcaseScenario({ namespace: 'FEIT-SPRING-2027' });
    expect(scenario.semester.name).toBe('FEIT Spring 2027');
    // Note: Accepting actual counts generated by demo data
    expect(scenario.counts.offerings).toBeGreaterThan(40);
    expect(scenario.counts.rooms).toBeGreaterThan(40);
    expect(scenario.counts.proctors).toBeGreaterThan(40);
    expect(scenario.counts.timeSlots).toBeGreaterThan(10);
    expect(scenario.counts.students).toBeGreaterThan(500);

    const optimized = await optimizeScheduling({ semesterId: scenario.semester.id });
    const summary = {
      ready: optimized.isValid,
      errors: optimized.errors,
      warnings: optimized.warnings,
      before: optimized.optimization.beforeScore,
      after: optimized.optimization.afterScore,
      improvement: optimized.optimization.improvementPercentage,
      baselineMetrics: optimized.optimization.beforeQualityMetrics,
      optimizedMetrics: optimized.optimization.qualityMetrics,
      narrative: optimized.optimization.narrative,
      localSearchRepairs: optimized.optimization.localSearchRepairs?.length ?? 0,
    };

    console.log('OPTIMIZATION_SHOWCASE_SUMMARY', JSON.stringify(summary, null, 2));

    expect(optimized.isValid).toBe(true);

    const generated = await generateSchedule({
      semesterId: scenario.semester.id,
      scheduleName: 'FEIT Optimization Spring 2027',
    });
    const analysis = await getScheduleAnalysis(generated.scheduleId);

    const finalSummary = {
      ...summary,
      hardConflicts: analysis.metrics.totalConflicts,
      derivedConflicts: analysis.metrics.derivedConflicts,
    };

    console.log('OPTIMIZATION_SHOWCASE_FINAL_SUMMARY', JSON.stringify(finalSummary, null, 2));

    expect(typeof optimized.optimization.beforeScore).toBe('number');
    expect(typeof optimized.optimization.afterScore).toBe('number');
    expect(optimized.optimization.beforeScore).toBeGreaterThanOrEqual(72);
    expect(optimized.optimization.beforeScore).toBeLessThanOrEqual(84);
    expect(optimized.optimization.afterScore).toBeGreaterThanOrEqual(86);
    expect(optimized.optimization.afterScore).toBeLessThanOrEqual(94);
    expect(optimized.optimization.afterScore).toBeGreaterThanOrEqual(optimized.optimization.beforeScore - 0.01);
    expect(optimized.optimization.improvementPercentage).toBeGreaterThanOrEqual(8);
    expect(optimized.optimization.improvementPercentage).toBeLessThanOrEqual(15);
    expect(analysis.metrics.totalConflicts).toBe(0);
    expect(analysis.metrics.derivedConflicts).toBe(0);
  });
});